# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DmfDaMequipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asset', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_da_mequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfDaOassets',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asset', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_da_oassets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfDaStructure',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asset', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_da_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfDaSupplies',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asset', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_da_supplies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfDfaNum',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('num_des_facilities', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.BigIntegerField(null=True, blank=True)),
                ('divisional_hospital', models.IntegerField(null=True, blank=True)),
                ('rural_hospital', models.BigIntegerField(null=True, blank=True)),
                ('central_dispensary', models.BigIntegerField(null=True, blank=True)),
                ('pmcus', models.BigIntegerField(null=True, blank=True)),
                ('phccs', models.BigIntegerField(null=True, blank=True)),
                ('mchcs', models.BigIntegerField(null=True, blank=True)),
                ('total', models.BigIntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_dfa_num',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfDfaPaf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('num_patients_affected', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.BigIntegerField(null=True, blank=True)),
                ('divisional_hospital', models.IntegerField(null=True, blank=True)),
                ('rural_hospital', models.BigIntegerField(null=True, blank=True)),
                ('central_dispensary', models.BigIntegerField(null=True, blank=True)),
                ('pmcus', models.BigIntegerField(null=True, blank=True)),
                ('phccs', models.BigIntegerField(null=True, blank=True)),
                ('mchcs', models.BigIntegerField(null=True, blank=True)),
                ('total', models.BigIntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_dfa_paf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfLosCud',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_of_losses', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_los_cud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfLosFi',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_of_losses', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_los_fi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfLosHoc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_of_losses', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_los_hoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfLosOue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_of_losses', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_los_oue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfPdaMequipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asset', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_pda_mequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfPdaOassets',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asset', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_pda_oassets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfPdaStructure',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asset', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pmcus', models.FloatField(null=True, blank=True)),
                ('phccs', models.FloatField(null=True, blank=True)),
                ('mchcs', models.FloatField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_pda_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfPdfaNum',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('num_pdamaged_facilities', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.BigIntegerField(null=True, blank=True)),
                ('divisional_hospital', models.BigIntegerField(null=True, blank=True)),
                ('rural_hospital', models.BigIntegerField(null=True, blank=True)),
                ('central_dispensary', models.BigIntegerField(null=True, blank=True)),
                ('pmcus', models.BigIntegerField(null=True, blank=True)),
                ('phccs', models.BigIntegerField(null=True, blank=True)),
                ('mchcs', models.BigIntegerField(null=True, blank=True)),
                ('total', models.BigIntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_pdfa_num',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmfPdfaPaf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('num_patients_affected', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.BigIntegerField(null=True, blank=True)),
                ('divisional_hospital', models.BigIntegerField(null=True, blank=True)),
                ('rural_hospital', models.BigIntegerField(null=True, blank=True)),
                ('central_dispensary', models.BigIntegerField(null=True, blank=True)),
                ('pmcus', models.BigIntegerField(null=True, blank=True)),
                ('phccs', models.BigIntegerField(null=True, blank=True)),
                ('mchcs', models.BigIntegerField(null=True, blank=True)),
                ('total', models.BigIntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dmf_pdfa_paf',
                'managed': False,
            },
        ),
    ]
