"""
Django settings for dala project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z(-pb7d!3-efta70vsay=by7=*ng#=9vayn@dc)9b8ddcg%54&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'report_builder',
    'incidents',
    'dashboard',
    # 'tastypie',
    'settings',
    'users',
    'reports',
    'charts',
    'health',
    'health.base_line',
    'health.damage_losses',
    'education',
    'education.base_line',
    'education.damage_losses',
    # 'db_tools'
    'other_govn_services',
    'other_govn_services.base_line',
    'other_govn_services.damage_losses',
    'mining.base_line',
    'mining.damage_losses',
    'mining',
    'transport_rail',
    'transport_rail.base_line',
    'transport_rail.damage_losses',
    'transport_water',
    'transport_water.base_line',
    'transport_water.damage_losses',
    'transport_land',
    'transport_land.base_line',
    'transport_land.damage_losses',
    'transport_air',
    'transport_air.base_line',
    'transport_air.damage_losses',
    'transport_summary',
    'transport_summary.damage_losses',
    'agri_agrarian',
    'agri_agrarian.base_line',
    'agri_agrarian.damage_losses',
    
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'dbtools.middleware.ReadOnlyMiddleware',
]

ROOT_URLCONF = 'dala.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dala.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'OPTIONS': {
        #     'options': '-c search_path=health,public,other_government,education,mining,transport_rail,transport_water,transport_land,transport_air,agri_agrarian'
        # },
        'NAME': 'dala_new',
        'USER': 'postgres',

    },

}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    )
}

REPORT_BUILDER_INCLUDE = ['health.damage_losses.models.DsnPubPnLmh', 'health.report_builder_report']

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# table properties
TABLE_PROPERTY_MAPPER = {
    'health': {
        'Table_1':
            {'BhsPlc': ['children', 'elderly', 'female', 'male', 'id'],
             'BhsComDiseases': ['com_disease', 'male', 'female', 'children', 'elderly', 'id'],
             'BhsVi': ['children', 'elderly', 'female', 'male', 'vital_indicators', 'id'],
             'BhsOi': ['unit_measure', 'other_indicators', 'id']
             },
        'Table_2':
            {
                'BmfPubMf': ['type_pub_mf', 'number', 'male', 'female', 'id'],
                'BmfPvtMf': ['type_pvt_mf', 'number', 'male', 'female', 'id']

            },
        'Table_8':
            {
                'DshPubLmh': ['facilities_assets', 'total_num_affected', 'male', 'female', 'total_damages',
                              'losses_y1', 'losses_y2', 'total_losses'],
                'DshPubMoh': ['facilities_assets', 'total_num_affected', 'male', 'female', 'total_damages',
                              'losses_y1', 'losses_y2', 'total_losses'],
                'DshPubOmf': ['facilities_assets', 'total_num_affected', 'male', 'female', 'total_damages',
                              'losses_y1', 'losses_y2', 'total_losses'],
                'DshPvtFa': ['facilities_assets', 'total_num_affected', 'male', 'female', 'total_damages',
                             'losses_y1', 'losses_y2', 'total_losses'],
                'DshTdlOwship': ['ownership', 'damages', 'losses_y1', 'losses_y2', 'total']
            },
        'Table_4':
            {
                'BucOmarStructure': ['particulars', 'base_hospital', 'divisional_hospital',
                                     'rural_hospital',
                                     'central_dispensary', 'pri_med_cunits', 'pri_health_ccenters',
                                     'mat_child_health_clinics', 'id'],
                'BucOmarSupplies': ['particulars', 'base_hospital', 'divisional_hospital',
                                    'rural_hospital',
                                    'central_dispensary', 'pri_med_cunits', 'pri_health_ccenters',
                                    'mat_child_health_clinics', 'id'],
                'BucOmarMequipment': ['particulars', 'base_hospital', 'divisional_hospital',
                                      'rural_hospital',
                                      'central_dispensary', 'pri_med_cunits', 'pri_health_ccenters',
                                      'mat_child_health_clinics', 'id'],
                'BucOmarOassets': ['particulars', 'base_hospital', 'divisional_hospital',
                                   'rural_hospital',
                                   'central_dispensary', 'pri_med_cunits', 'pri_health_ccenters',
                                   'mat_child_health_clinics', 'id'],
                'BucOmarcCrpm': ['particulars', 'base_hospital', 'divisional_hospital',
                                 'rural_hospital',
                                 'central_dispensary', 'pri_med_cunits',
                                 'pri_health_ccenters'                                 'mat_child_health_clinics',
                                 'id'],
                'BucOmarcStructure': ['particulars', 'base_hospital', 'divisional_hospital',
                                      'rural_hospital',
                                      'central_dispensary', 'pri_med_cunits', 'pri_health_ccenters',
                                      'mat_child_health_clinics', 'id'],
                'BucOmarcMequipment': ['particulars', 'base_hospital', 'divisional_hospital',
                                       'rural_hospital',
                                       'central_dispensary', 'pri_med_cunits',
                                       'pri_health_ccenters',
                                       'mat_child_health_clinics', 'id'],
                'BucOmarcOassets': ['particulars', 'base_hospital', 'divisional_hospital',
                                    'rural_hospital',
                                    'central_dispensary', 'pri_med_cunits', 'pri_health_ccenters',
                                    'mat_child_health_clinics', 'id']

            },
        'Table_10':
            {

                'DshPubLmhProvince': ['facilities_assets', 'total_num_affected', 'male', 'female',
                                      'total_damages', 'losses_y1',
                                      'losses_y2', 'total_losses', 'id'],
                'DshPubMohProvince': ['facilities_assets', 'total_num_affected', 'male', 'female',
                                      'total_damages', 'losses_y1',
                                      'losses_y2', 'total_losses', 'id'],
                'DshPubOmfProvince': ['facilities_assets', 'total_num_affected', 'male', 'female',
                                      'total_damages', 'losses_y1',
                                      'losses_y2', 'total_losses', 'id'],
                'DshPvtFaProvince': ['facilities_assets', 'total_num_affected', 'male', 'female',
                                     'total_damages', 'losses_y1',
                                     'losses_y2', 'total_losses', 'id'],

            },

        'Table_3':
            {
                'BucMarStructure': ['particulars', 'teaching_hospital', 'provincial_general_hospital',
                                    'district_general_hospital', 'office', 'other', 'id'],
                'BucMarSupplies': ['particulars', 'teaching_hospital', 'provincial_general_hospital',
                                   'district_general_hospital', 'id'],
                'BucMarMequipment': ['particulars', 'teaching_hospital', 'provincial_general_hospital',
                                     'district_general_hospital', 'id'],
                'BucMarOassets': ['particulars', 'teaching_hospital', 'provincial_general_hospital',
                                  'district_general_hospital', 'office', 'other', 'id'],
                'BucMarcStructures': ['particulars', 'teaching_hospital', 'provincial_general_hospital',
                                      'district_general_hospital', 'office', 'other', 'id'],
                'BucMarcMequipment': ['particulars', 'teaching_hospital', 'provincial_general_hospital',
                                      'district_general_hospital', 'id'],
                'BucMarcOassets': ['particulars', 'teaching_hospital', 'provincial_general_hospital',
                                   'district_general_hospital', 'office', 'other', 'id'],
                'BucMarcCrpm': ['particulars', 'teaching_hospital', 'provincial_general_hospital',
                                'district_general_hospital', 'office', 'other', 'id'],
            },
        'Table_5':
            {
                'DmhDfNum': ['num_des_facilities', 'teaching_hospital', 'provincial_general_hospital',
                             'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhDfPaf': ['num_patients_affected', 'teaching_hospital', 'provincial_general_hospital',
                             'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhNdatFacStructure': ['asset', 'teaching_hospital', 'provincial_general_hospital',
                                        'district_general_hospital', 'office', 'total', 'id'],
                'DmhNdatFacSupplies': ['asset', 'teaching_hospital', 'provincial_general_hospital',
                                       'district_general_hospital', 'total', 'id'],
                'DmhNdatFacMequipment': ['asset', 'teaching_hospital', 'provincial_general_hospital',
                                         'district_general_hospital', 'total', 'id'],
                'DmhNdatFacOassets': ['asset', 'teaching_hospital', 'provincial_general_hospital',
                                      'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhPdfaNum': ['num_des_facilities', 'teaching_hospital', 'provincial_general_hospital',
                               'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhPdfaPaf': ['num_patients_affected', 'teaching_hospital', 'provincial_general_hospital',
                               'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhPdfaStructure': ['asset', 'teaching_hospital', 'provincial_general_hospital',
                                     'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhPdfaMequipment': ['asset', 'teaching_hospital', 'provincial_general_hospital',
                                      'district_general_hospital', 'total', 'id'],
                'DmhPdfaOassets': ['asset', 'teaching_hospital', 'provincial_general_hospital',
                                   'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhLosFi': ['type_of_losses', 'teaching_hospital', 'provincial_general_hospital',
                             'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhLosCud': ['type_of_losses', 'teaching_hospital', 'provincial_general_hospital',
                              'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhLosHoc': ['type_of_losses', 'teaching_hospital', 'provincial_general_hospital',
                              'district_general_hospital', 'office', 'other', 'total', 'id'],
                'DmhLosOue': ['type_of_losses', 'teaching_hospital', 'provincial_general_hospital',
                              'district_general_hospital', 'office', 'other', 'total', 'id'],
            }, 'Table_7':
            {
                'DapNapTmf': ['type_med_fac', 'num_affected_fac', 'male', 'female', 'id'],

                'DapBefPc1': ['pvt_clinics', 'est_replacement_cost', 'est_repair_cost', 'total_damages',
                              'est_losses_y1', 'est_losses_y2', 'total_losses', 'id'],

                'DapBefPcn': ['pvt_clinics', 'est_replacement_cost', 'est_repair_cost', 'total_damages',
                              'est_losses_y1', 'est_losses_y2', 'total_losses', 'id'],
                'DapBefOther': ['pvt_clinics', 'est_replacement_cost', 'est_repair_cost', 'total_damages',
                                'est_losses_y1', 'est_losses_y2', 'total_losses', 'id']
            }, 'Table_9':
            {
                'DshPubLmhDistrict': ['facilities_assets', 'total_num_affected', 'male', 'female', 'total_damages',
                                      'losses_y1', 'losses_y2', 'total_losses', 'id', 'district'],
                'DshPubMohDistrict': ['facilities_assets', 'total_num_affected', 'male', 'female', 'total_damages',
                                      'losses_y1', 'losses_y2', 'total_losses', 'id', 'district'],
                'DshPubOmfDistrict': ['facilities_assets', 'total_num_affected', 'male', 'female', 'total_damages',
                                      'losses_y1', 'losses_y2', 'total_losses', 'id', 'district'],
                'DshPvtFaDistrict': ['facilities_assets', 'total_num_affected', 'male', 'female', 'total_damages',
                                     'losses_y1', 'losses_y2', 'total_losses', 'id', 'district']
            },
        'Table_6':
            {
                'DmfDfaNum': ['num_des_facilities',
                              'base_hospital',
                              'divisional_hospital',
                              'rural_hospital',
                              'central_dispensary',
                              'pmcus',
                              'phccs',
                              'mchcs',
                              'total', 'id'],
                'DmfDfaPaf': ['num_patients_affected',
                              'base_hospital',
                              'divisional_hospital',
                              'rural_hospital',
                              'central_dispensary',
                              'pmcus',
                              'phccs',
                              'mchcs',
                              'total', 'id'],
                'DmfDaStructure': ['asset',
                                   'base_hospital',
                                   'divisional_hospital',
                                   'rural_hospital',
                                   'central_dispensary',
                                   'pmcus',
                                   'phccs',
                                   'mchcs',
                                   'total', 'id'],
                'DmfDaSupplies': ['asset',
                                  'base_hospital',
                                  'divisional_hospital',
                                  'rural_hospital',
                                  'central_dispensary',
                                  'pmcus',
                                  'phccs',
                                  'mchcs',
                                  'total', 'id'],

                'DmfDaMequipment': ['asset',
                                    'base_hospital',
                                    'divisional_hospital',
                                    'rural_hospital',
                                    'central_dispensary',
                                    'pmcus',
                                    'phccs',
                                    'mchcs',
                                    'total', 'id'],

                'DmfDaOassets': ['asset',
                                 'base_hospital',
                                 'divisional_hospital',
                                 'rural_hospital',
                                 'central_dispensary',
                                 'pmcus',
                                 'phccs',
                                 'mchcs',
                                 'total', 'id'],

                'DmfPdfaNum': ['num_pdamaged_facilities',
                               'base_hospital',
                               'divisional_hospital',
                               'rural_hospital',
                               'central_dispensary',
                               'pmcus',
                               'phccs',
                               'mchcs',
                               'total', 'id'],

                'DmfPdfaPaf': ['num_patients_affected',
                               'base_hospital',
                               'divisional_hospital',
                               'rural_hospital',
                               'central_dispensary',
                               'pmcus',
                               'phccs',
                               'mchcs',
                               'total', 'id'],

                'DmfPdaStructure': ['asset',
                                    'base_hospital',
                                    'divisional_hospital',
                                    'rural_hospital',
                                    'central_dispensary',
                                    'pmcus',
                                    'phccs',
                                    'mchcs',
                                    'total', 'id'],

                'DmfPdaMequipment': ['asset',
                                     'base_hospital',
                                     'divisional_hospital',
                                     'rural_hospital',
                                     'central_dispensary',
                                     'pmcus',
                                     'phccs',
                                     'mchcs',
                                     'total', 'id'],

                'DmfPdaOassets': ['asset',
                                  'base_hospital',
                                  'divisional_hospital',
                                  'rural_hospital',
                                  'central_dispensary',
                                  'pmcus',
                                  'phccs',
                                  'mchcs',
                                  'total', 'id'],

                'DmfLosFi': ['type_of_losses',
                             'base_hospital',
                             'divisional_hospital',
                             'rural_hospital',
                             'central_dispensary',
                             'pmcus',
                             'phccs',
                             'mchcs',
                             'total', 'id'],

                'DmfLosCud': ['type_of_losses',
                              'base_hospital',
                              'divisional_hospital',
                              'rural_hospital',
                              'central_dispensary',
                              'pmcus',
                              'phccs',
                              'mchcs',
                              'total', 'id'],

                'DmfLosHoc': ['type_of_losses',
                              'base_hospital',
                              'divisional_hospital',
                              'rural_hospital',
                              'central_dispensary',
                              'pmcus',
                              'phccs',
                              'mchcs',
                              'total', 'id'],

                'DmfLosOue': ['type_of_losses',
                              'base_hospital',
                              'divisional_hospital',
                              'rural_hospital',
                              'central_dispensary',
                              'pmcus',
                              'phccs',
                              'mchcs',
                              'total', 'id']

            }

    },
    'mining': {
        'Table_1': {

            'BmaImFn': ['name_min_outputs',
                        'avg_per_year',
                        'firm_id',
                        'id'],
            'BmaImFirmNum': ['male',
                             'female',
                             'firm_id',
                             'id'],

        },
        'Table_2': {

            'BmaAmMin': ['minerals',
                         'avg_per_year', 'id'],
            'BmaAmMinNum': ['male',
                            'female',
                            'id'],

        },
        'Table_3': {
            'DloNumEmps': [
                'male', 'female', 'firm_id', 'id'],
            'DloDmgStructures': [
                'assets', 'rep_tot_dassets', 'repair_pdmg_assets', 'tot_damages', 'firm_id', 'id'],
            'DloDmgEquipment': [
                'assets', 'rep_tot_dassets', 'repair_pdmg_assets', 'tot_damages', 'firm_id', 'id'],
            'DloDmgMachinery': [
                'assets', 'rep_tot_dassets', 'repair_pdmg_assets', 'tot_damages', 'firm_id', 'id'],
            'DloDmgVehicles': [
                'assets', 'rep_tot_dassets', 'repair_pdmg_assets', 'tot_damages', 'firm_id', 'id'],
            'DloDmgStocks': [
                'assets', 'rep_tot_dassets', 'repair_pdmg_assets', 'tot_damages', 'firm_id', 'id'],
            'DloLosPlos': [
                'type_los', 'avg_per_year', 'red_voutput_year1', 'red_voutput_year2', 'los_year1', 'los_year2',
                'tot_losses', 'firm_id', 'id'],
            'DloLosOlos': [
                'type_los', 'los_year1', 'los_year2', 'tot_losses', 'firm_id', 'id']
        },
        'Table_4': {
            'DlaDmgStructures': [
                'assets',
                'rep_tot_dassets',
                'repair_pdmg_assets',
                'tot_damages',
                'id'
            ],
            'DlaDmgEquipment': [
                'assets',
                'rep_tot_dassets',
                'repair_pdmg_assets',
                'tot_damages',
                'id'
            ],
            'DlaDmgMachinery': [
                'assets',
                'rep_tot_dassets',
                'repair_pdmg_assets',
                'tot_damages',
                'id'
            ],
            'DlaDmgStocks': [
                'assets',
                'rep_tot_dassets',
                'repair_pdmg_assets',
                'tot_damages',
                'id'
            ],
            'DlaLosPlos': [
                'type_los',
                'avg_per_year',
                'red_voutput_year1',
                'red_voutput_year2',
                'los_year1',
                'los_year2',
                'tot_losses',
                'id'
            ],
            'DlaLosOlos': [
                'type_los',
                'avg_per_year',
                'red_voutput_year1',
                'red_voutput_year2',
                'los_year1',
                'los_year2',
                'tot_losses',
                'id'
            ]
        },
        'Table_5': {

            'DloDmgDistrict': [
                'rep_tot_dassets',
                'repair_pdmg_assets',
                'tot_damages',
                'firm__name',
                'ownership'

            ],
            'DlaDmgDistrict': [
                'rep_tot_dassets',
                'repair_pdmg_assets',
                'tot_damages'
            ],

            'DlaLosDistrict': [
                'los_year1',
                'los_year2',
                'tot_losses'
            ],
            'DloLosDistrict': [
                'los_year1',
                'los_year2',
                'tot_losses',
                'firm__name',
                'ownership'

            ],

        },
        'Table_6': {

            'DlaDmgNational': [
                'tot_damages',

            ],
            'DlaLosNational': [
                'los_year1',
                'los_year2',
                'tot_losses',
            ],
            'DloDmgNational': [
                'tot_damages',
                'ownership'
            ],
            'DloLosNational': [
                'los_year1',
                'los_year2',
                'tot_losses',
                'ownership'
            ],

        }

    },
    'other_govn_services': {
        'Table_3': {
            'DlagdDmgDistrict': [
                'damages',
                'department__name'
            ],
            'DlagdLossesDistrict': [
                'los_year1',
                'los_year2',
                'total_losses',
                'department__name'
            ]
        },
        'Table_4': {
            'DlagdDmgProvince': [
                'damages',
            ],
            'DlagdLossesProvince': [
                'los_year1',
                'los_year2',
                'total_losses',
            ]
        },
        'Table_5': {
            'DlagdDmgNational': [
                'damages',
            ],
            'DlagdLossesNational': [
                'los_year1',
                'los_year2',
                'total_losses'
            ]
        },
        'Table_2': {
            'DlagdDmgStructure': [
                'name_dept',
                'td_num_structures',
                'td_total_squarem',
                'pd_num_structures',
                'pd_total_squarem_roof',
                'pd_total_squarem_wall',
                'pd_total_squarem_floor',
                'damages',
                'id'
            ],
            'DlagdDmgOfficeEquipment': [
                'name_dept',
                'num_tot_destroyed',
                'num_partial_damaged',
                'damages',
                'id'
            ],
            'DlagdDmgMachinery': [
                'name_dept',
                'num_tot_destroyed',
                'num_partial_damaged',
                'damages',
                'id'
            ],
            'DlagdLosses': [
                'name_dept',
                'los_year1',
                'los_year2',
                'total_losses',
                'id'
            ]
        }
    },
    'education': {
        'Table_3': {
            'DugDfNdf': [
                'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges', 'tc_crc_resc',
                'min_pzd_offices', 'total'
            ],
            'DugDfNsa': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'total'
            ],
            'DugNdafStructure': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugNdafSupplies': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugNdafEquipment': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugPdfaNpdf': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugPdfaNsa': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugNpdatStructure': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugNpdatSupplies': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugNpdatEquipment': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugLosFi': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugLosCud': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugLosHoc': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
            'DugLosOue': [
                'particulars', 'ab1_1c', 'type_2', 'type_3', 'pirivena', 'training_institutes', 'training_colleges',
                'tc_crc_resc', 'min_pzd_offices', 'total'
            ],
        },
        'Table_4': {
            'DpefNaf': ['edu_facilities', 'num_edu_facilities', 'male', 'female'],
            'DpefBefPreSchool': ['asset', 'pre_school', 'est_rep_cost', 'est_repair_cost', 'tot_damages',
                                 'est_los_year_1', 'est_los_year_2', 'tot_los'],
            'DpefBefPrmSchool': ['asset', 'pre_school', 'est_rep_cost', 'est_repair_cost', 'tot_damages',
                                 'est_los_year_1', 'est_los_year_2', 'tot_los'],
            'DpefBefSecSchool': ['asset', 'pre_school', 'est_rep_cost', 'est_repair_cost', 'tot_damages',
                                 'est_los_year_1', 'est_los_year_2', 'tot_los'],
            'DpefBefUnv': ['asset', 'pre_school', 'est_rep_cost', 'est_repair_cost', 'tot_damages', 'est_los_year_1',
                           'est_los_year_2', 'tot_los'],
            'DpefBefTechInst': ['asset', 'pre_school', 'est_rep_cost', 'est_repair_cost', 'tot_damages',
                                'est_los_year_1', 'est_los_year_2', 'tot_los']
        },
        'Table_2': {
            'BugArcStructures': [
                'particulars',
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
                'id'
            ],
            'BugArcSupplies': [
                'particulars',
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
                'id'],
            'BugArcEquipment': [
                'particulars',
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
                'id'],
            'BugArpcStructures': [
                'particulars',
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
                'id'],
            'BugArpcSupplies': [
                'particulars',
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
                'id'],
            'BugArpcEquipment': [
                'particulars',
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
                'id'],
            'BugAfr': [
                'particulars',
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
                'id'],
            'BugCrp': [
                'particulars',
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
                'id']
        },
        'Table_5': {

            'DpefBefDistrict': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',
            ],
            'DpefBefPreDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefPrimaryDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefSecondaryDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefTechDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefUnvDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DugDfDistrict': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',

            ],
            'DugNsaDistrict': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',

            ],
            'DpefNaf': [
                'edu_facilities',
                'num_edu_facilities',
                'male',
                'female',
                'id',
            ],
            'DugNdafDistrict': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',

            ],

        },
        'Table_6': {

            'DpefBefDistrict': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',

            ],
            'DpefBefPreDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefPrimaryDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',
            ],
            'DpefBefSecondaryDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefTechDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',
            ],
            'DpefBefUnvDistrict': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',
            ],
            'DugDfDistrict': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',

            ],
            'DugNsaDistrict': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',

            ],
            'DpefNaf': [
                'edu_facilities',
                'num_edu_facilities',
                'male',
                'female',
                'id',
            ],
            'DugNdafDistrict': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',

            ],

        },
        'Table_7': {

            'DpefBefOtherNational': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefPreNational': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefPrimaryNational': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefPrimaryNational': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefSecondaryNational': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefTechNational': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefBefUnvNational': [
                'est_rep_cost',
                'est_repair_cost',
                'tot_damages',
                'est_los_year_1',
                'est_los_year_2',
                'tot_los',

            ],
            'DpefNafNational': [
                'num_edu_facilities',
                'male',
                'female',

            ],
            'DpefBefNational': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',

            ],
            'DugDfNational': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',

            ],
            'DugNdafNational': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',
                'min_pzd_offices',

            ],
            'DugNsaNational': [
                'ab1_1c',
                'type_2',
                'type_3',
                'pirivena',
                'training_institutes',
                'training_colleges',
                'tc_crc_resc',

            ],
        },

    },
    'transport_rail': {
        'Table_1': {

            'BsMovingAst':
                ['asset',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsEquipMachineryAst':
                ['asset',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsMatSuppliesAst':
                ['asset',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsStructuresAst':
                ['asset',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsBuildingAst': [
                'asset',
                'avg_replace_cost',
                'avg_repair_cost_roof',
                'avg_repair_cost_wall',
                'avg_repair_cost_floor',
                'id'
            ],
        },
        'Table_3': {

            'TotDmgProvince':
                ['tot_damages',
                 ],

        },
        'Table_4': {

            'TotDmgNational':
                ['tot_damages',
                 ],

        },
        'Table_5': {
            'DlTypeLos':
                ['loss_type', 'year_1', 'year_2', 'tot_los', 'id'],
        }

    },
    'transport_water': {
        'Table_1': {
            'BsAstWaterWcrafts':
                ['assets',
                 'public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsAstWaterEquipment':
                ['assets',
                 'public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsAstWaterMaterials':
                ['assets',
                 'public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsAstWaterStructures':
                ['assets',
                 'public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsAstWaterBuildings':
                ['assets',
                 'public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost_roof',
                 'avg_repair_cost_wall',
                 'avg_repair_cost_floor',
                 'id'],
            'BsAstWaterEmployment':
                ['assets',
                 'public',
                 'private',
                 'male',
                 'female',
                 'id'],

        },
        'Table_3': {
            'DlWaterDmgPubProvince':
                ['tot_dmg_public'],
            'DlWaterDmgPvtProvince':
                ['tot_dmg_private'],
            'DlWaterLosProvince':
                ['year_1_pub',
                 'year_2_pub',
                 'year_1_pvt',
                 'year_2_pvt'],

        },
        'Table_4': {
            'DlWaterDmgPubNational':
                ['tot_dmg_public'],
            'DlWaterDmgPvtNational':
                ['tot_dmg_private'],
            'DlWaterLosNational':
                ['year_1_pub',
                 'year_2_pub',
                 'year_1_pvt',
                 'year_2_pvt'],

        }

    },
    'transport_land': {
        'Table_3': {
            'BiaGacLandStructure':
                ['asset',
                 'avg_repair_cost',
                 'id'],
            'BiaGacLandPbuilding':
                ['asset',
                 'avg_repair_cost_floor_1',
                 'avg_repair_cost_floor_2_3',
                 'avg_repair_cost_floor_more_3',
                 'id'],
            'BiaGacLandOequipment':
                ['asset',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],

            'BiaGacLandMachinery':
                ['asset',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
        },
        'Table_2': {
            'BsGtlAstBcompanies':
                ['bus_companies',
                 'public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsGtlAstPvehicles':
                ['private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'private_vehicles',
                 'id'],
            'BsGtlAstTcompanies':
                ['public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'taxi_companies',
                 'id'],
            'BsGtlAstTrcompanies':
                ['public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'truck_companies',
                 'id'],
            'BsGtlAstTucompanies':
                ['public',
                 'private',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'tuk_companies',
                 'id'],

        },
        'Table_1': {
            'BsRbuRclassificattion':
                ['road_classification',
                 'avg_replace_concrete',
                 'avg_replace_asphalt',
                 'avg_replace_gravel',
                 'avg_replace_earth',
                 'avg_repair_concrete',
                 'avg_repair_asphalt',
                 'avg_repair_gravel',
                 'avg_repair_earth',
                 'id'],
            'BsRbuTbridges':
                ['type_bridges',
                 'avg_replace_2_lanes',
                 'avg_replace_multi_lanes',
                 'avg_repair_2_lanes',
                 'avg_repair_multi_lanes',
                 'id'],
            'BsRbuTrwalls':
                ['type_retain_walls',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsRbuTculverts':
                ['type_culverts',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsRbuTdrains':
                ['type_drains',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],

        },
        'Table_4': {
            'DlRbdTbridges':
                ['tot_dest_2_lanes',
                 'tot_dest_multi_lanes',
                 'part_dest_2_lanes',
                 'part_dest_multi_lanes',
                 'part_dest_gravel',
                 'part_dest_earth',
                 'damages',
                 'type_bridges',
                 'id'],
            'DlRbdTculverts':
                ['tot_destroyed',
                 'part_destroyed',
                 'damages',
                 'type_culverts',
                 'id'],
            'DlRbdTrwalls':
                ['tot_destroyed',
                 'part_destroyed',
                 'damages',
                 'type_retain_walls',
                 'id'],
            'DlRbdTdrains':
                ['tot_destroyed',
                 'part_destroyed',
                 'damages',
                 'type_drains',
                 'id'],
            'DlOtherDmgsPvehicles':
                ['num_tot_dest_pvt',
                 'num_part_dest_pvt',
                 'tot_damages_pvt',
                 'private_vehicles',
                 'id'],
            'DlRbdRclassification':
                ['tot_dest_concrete',
                 'tot_dest_asphalt',
                 'tot_dest_gravel',
                 'tot_dest_earth',
                 'part_dest_concrete',
                 'part_dest_asphalt',
                 'part_dest_gravel',
                 'part_dest_earth',
                 'damages',
                 'road_classification',
                 'id'],
            'DlRbdLosses':
                ['year_1',
                 'year_2',
                 'part_destroyed',
                 'losses',
                 'loss_type',
                 'id'],

        },
        'Table_5': {
            'DlOtherDmgsPvehicles':
                ['num_tot_dest_pvt',
                 'num_part_dest_pvt',
                 'tot_damages_pvt',
                 'private_vehicles',
                 'id'],
            'DlOtherDmgsBcompanies':
                ['num_tot_dest_pub',
                 'num_tot_dest_pvt',
                 'num_part_dest_pub',
                 'num_part_dest_pvt',
                 'tot_damages_pub',
                 'tot_damages_pvt',
                 'bus_companies',
                 'id'],
            'DlOtherDmgsTcompanies':
                ['num_tot_dest_pub',
                 'num_tot_dest_pvt',
                 'num_part_dest_pub',
                 'num_part_dest_pvt',
                 'tot_damages_pub',
                 'tot_damages_pvt',
                 'taxi_companies',
                 'id'],
            'DlOtherDmgsTrcompanies':
                ['num_tot_dest_pub',
                 'num_tot_dest_pvt',
                 'num_part_dest_pub',
                 'num_part_dest_pvt',
                 'tot_damages_pub',
                 'tot_damages_pvt',
                 'truck_companies',
                 'id'],
            'DlOtherDmgsTucompanies':
                ['num_tot_dest_pub',
                 'num_tot_dest_pvt',
                 'num_part_dest_pub',
                 'num_part_dest_pvt',
                 'tot_damages_pub',
                 'tot_damages_pvt',
                 'tuk_companies',
                 'id'],
            'DlOtherLosPub':
                ['fi_year_1',
                 'fi_year_2',
                 'cl_debris_year_1',
                 'cl_debris_year_2',
                 'hoc_year_1',
                 'hoc_year_2',
                 'oue_year_1',
                 'oue_year_2',
                 'tot_los',
                 'tr_company',
                 'id'],
            'DlOtherLosPvt':
                ['fi_year_1',
                 'fi_year_2',
                 'cl_debris_year_1',
                 'cl_debris_year_2',
                 'hoc_year_1',
                 'hoc_year_2',
                 'oue_year_1',
                 'oue_year_2',
                 'tot_los',
                 'tr_company',
                 'id'],

        },
        'Table_7': {
            'DlRbdRclassificationDistrict':
                ['damages', 'incident', 'district'],
            'DlRbdTbridgesDistrict':
                ['damages', 'incident', 'district'],
            'DlRbdTculvertsDistrict':
                ['damages', 'incident', 'district'],
            'DlRbdTdrainsDistrict':
                ['damages', 'incident', 'district'],
            'DlRbdTrwallsDistrict':
                ['damages', 'incident', 'district'],
            'DlOtherDmgsPvehiclesDistrict':
                ['tot_damages_pvt', 'incident', 'district'],
            'DlOtherDmgsBcompaniesDistrict':
                ['tot_damages_pub', 'tot_damages_pvt', 'incident', 'district'],
            'DlOtherDmgsTcompaniesDistrict':
                ['tot_damages_pub', 'tot_damages_pvt', 'incident', 'district'],
            'DlOtherDmgsTrcompaniesDistrict':
                ['tot_damages_pub', 'tot_damages_pvt', 'incident', 'district'],
            'DlOtherDmgsTucompaniesDistrict':
                ['tot_damages_pub', 'tot_damages_pvt', 'incident', 'district'],
            'DlGacPubDistrict':
                ['damages', 'incident', 'district'],

        },
        'Table_6': {
            'DlGacDmgStructures':
                ['assets',
                 'num_tot_destroyed',
                 'num_square_meters',
                 'damages',
                 'id'],
            'DlGacLosType':
                ['assets',
                 'los_year_1',
                 'los_year_2',
                 'total',
                 'id'],
            'DlGacPdmgEquipment':
                ['assets',
                 'num_tot_destroyed',
                 'num_part_damaged',
                 'damages',
                 'id'],
            'DlGacPdmgMachinery':
                ['assets',
                 'num_tot_destroyed',
                 'num_part_damaged',
                 'damages',
                 'id'],
            'DlGacPdmgStructures':
                ['assets',
                 'num_part_damaged',
                 'damaged_roof',
                 'damaged_walls',
                 'damaged_floors',
                 'damages',
                 'id'],

        },
        'Table_8': {
            'DlGacPubProvince':
                ['damages'],
            'DlGacPvtProvince':
                ['tot_damages_pvt'],
            'DlYearsPubProvince':
                ['year_1',
                 'year_2',
                 ],
            'DlOtherLosPvtDistrict':
                ['year_1_pvt',
                 'year_2_pub',
                 ],

        },
        'Table_9': {
            'DlGacPubNational':
                ['damages'],
            'DlGacPvtNational':
                ['tot_damages_pvt'],
            'DlOtherLosPvtNational':
                ['year_1_pvt',
                 'year_2_pub',
                 ],
            'DlYearsPubNational':
                ['year_1',
                 'year_2',
                 ],
        },
    },
    'transport_air': {
        'Table_1': {
            'BsAstAirAircrafts':
                ['assets',
                 'num_pub',
                 'num_pvt',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsAstAirEquipment':
                ['assets',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsAstAirSupplies':
                ['assets',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsAstAirOthers':
                ['assets',
                 'avg_replace_cost',
                 'avg_repair_cost',
                 'id'],
            'BsAstAirStructures':
                ['assets',
                 'repc_1_floor',
                 'repc_2_3_floor',
                 'repc_moret_3_floor',
                 'repairc_roof',
                 'repairc_wall',
                 'repairc_floor',
                 'id'],

            'BsAstAirEmployment':
                ['assets',
                 'male',
                 'female',
                 'total',
                 'id'],
        },
        'Table_2': {

            'DlAirDmgAircrafts': ['tot_destroyed_pub', 'tot_destroyed_pvt', 'tot_dmg_pub', 'tot_dmg_pvt',
                                  'part_damaged_pub', 'part_damaged_pvt', 'assets', 'id'],
            'DlAirDmgEquipment': ['tot_destroyed', 'part_damaged', 'tot_dmg_pub', 'assets', 'id'],

            'DlAirDmgSupplies': ['tot_destroyed_pub', 'tot_destroyed_pvt', 'tot_dmg_pub', 'tot_dmg_pvt',
                                 'part_damaged_pub', 'part_damaged_pvt', 'assets', 'id'],
            'DlAirDmgOthers': ['tot_destroyed', 'part_damaged', 'tot_dmg_pub', 'assets', 'id'],

            'DlAirDmgGstructures': ['tdest_floor_1', 'tdest_floor_2_3', 'tdest_floor_than_3', 'pdmg_number',
                                    'pdmg_roof', 'pdmg_wall', 'pdmg_floor', 'tot_pub', 'assets', 'id'],
            'DlAirLosFi': ['year_1_pub', 'year_1_pvt', 'year_2_pub', 'year_2_pvt', 'tot_los_pub', 'tot_los_pvt',
                           'type_los', 'id'],

            'DlAirLosHoc': ['year_1_pub', 'year_1_pvt', 'year_2_pub', 'year_2_pvt', 'tot_los_pub', 'tot_los_pvt',
                            'type_los', 'id'],

            'DlAirLosOther': ['year_1_pub', 'year_1_pvt', 'year_2_pub', 'year_2_pvt', 'tot_los_pub', 'tot_los_pvt',
                              'assets', 'id']
        },
        'Table_3': {
            'DlAirDmgAircraftsDistrict':
                ['tot_destroyed_pub', 'tot_destroyed_pvt', 'incident', 'district'],
            'DlAirDmgGstructuresDistrict':
                ['tot_pub', 'incident', 'district'],
            'DlAirDmgEquipmentDistrict':
                ['tot_dmg_pub', 'incident', 'district'],
            'DlAirDmgSuppliesDistrict':
                ['tot_dmg_pub', 'tot_dmg_pvt', 'incident', 'district'],
            'DlAirDmgOthersDistrict':
                ['tot_dmg_pub', 'incident', 'district'],

            'DlAirLosFiDistrict':
                ['year_1_pub', 'year_1_pvt', 'year_2_pub', 'year_2_pvt', 'tot_los_pub', 'tot_los_pvt', 'incident', 'district'],
            'DlAirLosHocDistrict':
                ['tot_dmg_pub', 'incident', 'district'],
        },
        'Table_4': {
            'DlAirDmgPubProvince':
                ['tot_destroyed_pub'],
            'DlAirDmgPvtProvince':
                ['tot_destroyed_pvt'],
            'DlAirLosProvince':
                ['year_1_pub', 'year_1_pvt', 'year_2_pub', 'year_2_pvt'],
        },
        'Table_5': {
            'DlAirDmgPubNational':
                ['tot_destroyed_pub'],
            'DlAirDmgPvtNational':
                ['tot_destroyed_pvt'],
            'DlAirLosNational':
                ['year_1_pub', 'year_1_pvt', 'year_2_pub', 'year_2_pvt'],
        }
    },
    # 'transport_summary': {
    #     'Table_1': {
    #         'DlGacPubProvince': ['damages'],
    #         'DlGacPvtProvince': ['tot_damages_pvt'],
    #         'DlYearsPubProvince': ['year_1', 'year_2'],
    #         'DlOtherLosPvtDistrict': ['year_1_pvt', 'year_2_pub', ],
    #         'DlAirDmgPubProvince': ['tot_destroyed_pub'],
    #         'DlAirDmgPvtProvince': ['tot_destroyed_pvt'],
    #         'DlAirLosProvince': ['year_1_pub', 'year_1_pvt', 'year_2_pub', 'year_2_pvt'],
    #         'DlWaterDmgPubProvince': ['tot_dmg_public'],
    #         'DlWaterDmgPvtProvince': ['tot_dmg_private'],
    #         'DlWaterLosProvince': ['year_1_pub', 'year_2_pub', 'year_1_pvt', 'year_2_pvt'],
    #         'TotDmgProvince': ['tot_damages'],
    #     },
    #     'Table_3': {
    #         'DlGacPubNational': ['damages'],
    #         'DlGacPvtNational': ['tot_damages_pvt'],
    #         'DlOtherLosPvtNational': ['year_1_pvt', 'year_2_pub'],
    #         'DlYearsPubNational': ['year_1', 'year_2'],
    #         'TotDmgNational': ['tot_damages'],
    #         'DlAirDmgPubNational': ['tot_destroyed_pub'],
    #         'DlAirDmgPvtNational': ['tot_destroyed_pvt'],
    #         'DlAirLosNational': ['year_1_pub', 'year_1_pvt', 'year_2_pub', 'year_2_pvt'],
    #         'DlWaterDmgPubNational': ['tot_dmg_public'],
    #         'DlWaterDmgPvtNational': ['tot_dmg_private'],
    #         'DlWaterLosNational': ['year_1_pub', 'year_2_pub', 'year_1_pvt', 'year_2_pvt'],
    #     }
    #
    # },
    'agri_agrarian': {
        'Table_1': {
            'BcagSeasonalCrops':
                ['seasonal_crops',
                 'areas_cultivated',
                 'avg_val_land',
                 'num_families',
                 'num_male',
                 'num_female',
                 'id'],
            'BcagPlantnCrops':
                ['plantn_crops',
                 'areas_cultivated',
                 'avg_val_land',
                 'num_families',
                 'num_male',
                 'num_female',
                 'id'],
            'BcagExportCrops':
                ['export_crops',
                 'areas_cultivated',
                 'avg_val_land',
                 'num_families',
                 'num_male',
                 'num_female',
                 'id'],
            'BcagForestry':
                ['forestry',
                'avg_value',
                'productn_pub',
                'productn_pvt',
                'productn_cost_nplanted',
                'productn_cost_mstage',
                'productn_cost_hstage',
                 'id'],
            'BacfOther':
                ['other_products',
                'avg_value',
                'productn_pub',
                'productn_pvt',
                'productn_cost_nplanted',
                'productn_cost_mstage',
                'productn_cost_hstage',
                 'id'],
        }

    },


}

AUTH_USER_MODEL = 'users.MyUser'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.RemoteUserBackend',
    'django.contrib.auth.backends.ModelBackend',
)
