# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BdSessionKeys',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('data_type', models.CharField(max_length=120, null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('date', models.DateTimeField(null=True, blank=True)),
                ('user', models.IntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'bd_session_keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BhsComDiseases',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_disease', models.CharField(max_length=255, null=True, blank=True)),
                ('male', models.IntegerField(null=True, blank=True)),
                ('female', models.IntegerField(null=True, blank=True)),
                ('children', models.IntegerField(null=True, blank=True)),
                ('elderly', models.IntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('session_id', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'bhs_com_diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BhsOi',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('other_indicators', models.CharField(max_length=255, null=True, blank=True)),
                ('male', models.IntegerField(null=True, blank=True)),
                ('female', models.IntegerField(null=True, blank=True)),
                ('children', models.IntegerField(null=True, blank=True)),
                ('elderly', models.IntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('session_id', models.BigIntegerField(null=True, blank=True)),
                ('unit_measure', models.CharField(max_length=255, null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'bhs_oi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BhsPlc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('male', models.IntegerField(null=True, blank=True)),
                ('female', models.IntegerField(null=True, blank=True)),
                ('children', models.IntegerField(null=True, blank=True)),
                ('elderly', models.IntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('session_id', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'bhs_plc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BhsVi',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('vital_indicators', models.CharField(max_length=255, null=True, blank=True)),
                ('male', models.IntegerField(null=True, blank=True)),
                ('female', models.IntegerField(null=True, blank=True)),
                ('children', models.IntegerField(null=True, blank=True)),
                ('elderly', models.IntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('session_id', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'bhs_vi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmfPubMf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_pub_mf', models.CharField(max_length=255, null=True, blank=True)),
                ('number', models.IntegerField(null=True, blank=True)),
                ('male', models.IntegerField(null=True, blank=True)),
                ('female', models.IntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=20, null=True, blank=True)),
            ],
            options={
                'db_table': 'bmf_pub_mf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmfPvtMf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type_pvt_mf', models.CharField(max_length=255, null=True, blank=True)),
                ('number', models.IntegerField(null=True, blank=True)),
                ('male', models.IntegerField(null=True, blank=True)),
                ('female', models.IntegerField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=20, null=True, blank=True)),
            ],
            options={
                'db_table': 'bmf_pvt_mf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucMarcCrpm',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('teaching_hospital', models.FloatField(null=True, blank=True)),
                ('provincial_general_hospital', models.FloatField(null=True, blank=True)),
                ('district_general_hospital', models.FloatField(null=True, blank=True)),
                ('office', models.FloatField(null=True, blank=True)),
                ('other', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_marc_crpm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucMarcMequipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('teaching_hospital', models.FloatField(null=True, blank=True)),
                ('provincial_general_hospital', models.FloatField(null=True, blank=True)),
                ('district_general_hospital', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_marc_mequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucMarcOassets',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('teaching_hospital', models.FloatField(null=True, blank=True)),
                ('provincial_general_hospital', models.FloatField(null=True, blank=True)),
                ('district_general_hospital', models.FloatField(null=True, blank=True)),
                ('office', models.FloatField(null=True, blank=True)),
                ('other', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_marc_oassets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucMarcStructures',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('teaching_hospital', models.FloatField(null=True, blank=True)),
                ('provincial_general_hospital', models.FloatField(null=True, blank=True)),
                ('district_general_hospital', models.FloatField(null=True, blank=True)),
                ('office', models.FloatField(null=True, blank=True)),
                ('other', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_marc_structures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucMarMequipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('teaching_hospital', models.FloatField(null=True, blank=True)),
                ('provincial_general_hospital', models.FloatField(null=True, blank=True)),
                ('district_general_hospital', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_mar_mequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucMarOassets',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('teaching_hospital', models.FloatField(null=True, blank=True)),
                ('provincial_general_hospital', models.FloatField(null=True, blank=True)),
                ('district_general_hospital', models.FloatField(null=True, blank=True)),
                ('office', models.FloatField(null=True, blank=True)),
                ('other', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_mar_oassets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucMarStructure',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('teaching_hospital', models.FloatField(null=True, blank=True)),
                ('provincial_general_hospital', models.FloatField(null=True, blank=True)),
                ('district_general_hospital', models.FloatField(null=True, blank=True)),
                ('office', models.FloatField(null=True, blank=True)),
                ('other', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=10, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_mar_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucMarSupplies',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('teaching_hospital', models.FloatField(null=True, blank=True)),
                ('provincial_general_hospital', models.FloatField(null=True, blank=True)),
                ('district_general_hospital', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_mar_supplies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucOmarcCrpm',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pri_med_cunits', models.FloatField(null=True, blank=True)),
                ('pri_health_ccenters', models.FloatField(null=True, blank=True)),
                ('mat_child_health_clinics', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_omarc_crpm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucOmarcMequipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pri_med_cunits', models.FloatField(null=True, blank=True)),
                ('pri_health_ccenters', models.FloatField(null=True, blank=True)),
                ('mat_child_health_clinics', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_omarc_mequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucOmarcOassets',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pri_med_cunits', models.FloatField(null=True, blank=True)),
                ('pri_health_ccenters', models.FloatField(null=True, blank=True)),
                ('mat_child_health_clinics', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_omarc_oassets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucOmarcStructure',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pri_med_cunits', models.FloatField(null=True, blank=True)),
                ('pri_health_ccenters', models.FloatField(null=True, blank=True)),
                ('mat_child_health_clinics', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_omarc_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucOmarMequipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pri_med_cunits', models.FloatField(null=True, blank=True)),
                ('pri_health_ccenters', models.FloatField(null=True, blank=True)),
                ('mat_child_health_clinics', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_omar_mequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucOmarOassets',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pri_med_cunits', models.FloatField(null=True, blank=True)),
                ('pri_health_ccenters', models.FloatField(null=True, blank=True)),
                ('mat_child_health_clinics', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_omar_oassets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucOmarStructure',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pri_med_cunits', models.FloatField(null=True, blank=True)),
                ('pri_health_ccenters', models.FloatField(null=True, blank=True)),
                ('mat_child_health_clinics', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_omar_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucOmarSupplies',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('particulars', models.CharField(max_length=255, null=True, blank=True)),
                ('base_hospital', models.FloatField(null=True, blank=True)),
                ('divisional_hospital', models.FloatField(null=True, blank=True)),
                ('rural_hospital', models.FloatField(null=True, blank=True)),
                ('central_dispensary', models.FloatField(null=True, blank=True)),
                ('pri_med_cunits', models.FloatField(null=True, blank=True)),
                ('pri_health_ccenters', models.FloatField(null=True, blank=True)),
                ('mat_child_health_clinics', models.FloatField(null=True, blank=True)),
                ('created_user', models.IntegerField(null=True, blank=True)),
                ('lmu', models.IntegerField(null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('lmd', models.DateTimeField(null=True, blank=True)),
                ('key', models.BigIntegerField(null=True, blank=True)),
                ('bs_date', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'buc_omar_supplies',
                'managed': False,
            },
        ),
    ]
